{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "a0a9958f",
   "metadata": {},
   "outputs": [],
   "source": [
    "import json\n",
    "import pandas as pd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "8fccd9ca",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>team1</th>\n",
       "      <th>team2</th>\n",
       "      <th>winner</th>\n",
       "      <th>margin</th>\n",
       "      <th>ground</th>\n",
       "      <th>matchDate</th>\n",
       "      <th>scorecard</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Namibia</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>Namibia</td>\n",
       "      <td>55 runs</td>\n",
       "      <td>Geelong</td>\n",
       "      <td>Oct 16, 2022</td>\n",
       "      <td>T20I # 1823</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Netherlands</td>\n",
       "      <td>U.A.E.</td>\n",
       "      <td>Netherlands</td>\n",
       "      <td>3 wickets</td>\n",
       "      <td>Geelong</td>\n",
       "      <td>Oct 16, 2022</td>\n",
       "      <td>T20I # 1825</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Scotland</td>\n",
       "      <td>West Indies</td>\n",
       "      <td>Scotland</td>\n",
       "      <td>42 runs</td>\n",
       "      <td>Hobart</td>\n",
       "      <td>Oct 17, 2022</td>\n",
       "      <td>T20I # 1826</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Ireland</td>\n",
       "      <td>Zimbabwe</td>\n",
       "      <td>Zimbabwe</td>\n",
       "      <td>31 runs</td>\n",
       "      <td>Hobart</td>\n",
       "      <td>Oct 17, 2022</td>\n",
       "      <td>T20I # 1828</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Namibia</td>\n",
       "      <td>Netherlands</td>\n",
       "      <td>Netherlands</td>\n",
       "      <td>5 wickets</td>\n",
       "      <td>Geelong</td>\n",
       "      <td>Oct 18, 2022</td>\n",
       "      <td>T20I # 1830</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "         team1        team2       winner     margin   ground     matchDate  \\\n",
       "0      Namibia    Sri Lanka      Namibia    55 runs  Geelong  Oct 16, 2022   \n",
       "1  Netherlands       U.A.E.  Netherlands  3 wickets  Geelong  Oct 16, 2022   \n",
       "2     Scotland  West Indies     Scotland    42 runs   Hobart  Oct 17, 2022   \n",
       "3      Ireland     Zimbabwe     Zimbabwe    31 runs   Hobart  Oct 17, 2022   \n",
       "4      Namibia  Netherlands  Netherlands  5 wickets  Geelong  Oct 18, 2022   \n",
       "\n",
       "     scorecard  \n",
       "0  T20I # 1823  \n",
       "1  T20I # 1825  \n",
       "2  T20I # 1826  \n",
       "3  T20I # 1828  \n",
       "4  T20I # 1830  "
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "with open('C:/Users/Dell/Desktop/python study material/t20_wc_match_results.json') as f:\n",
    " data = json.load(f)\n",
    "df_match=pd.DataFrame(data[0]['matchSummary'])\n",
    "df_match.head()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "4b91f8fe",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>match</th>\n",
       "      <th>teamInnings</th>\n",
       "      <th>battingPos</th>\n",
       "      <th>batsmanName</th>\n",
       "      <th>dismissal</th>\n",
       "      <th>runs</th>\n",
       "      <th>balls</th>\n",
       "      <th>4s</th>\n",
       "      <th>6s</th>\n",
       "      <th>SR</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>U.A.E.</td>\n",
       "      <td>1</td>\n",
       "      <td>Chirag Suri</td>\n",
       "      <td>c â€ Edwards b van der Merwe</td>\n",
       "      <td>12</td>\n",
       "      <td>20</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>60.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>U.A.E.</td>\n",
       "      <td>2</td>\n",
       "      <td>Muhammad Waseem</td>\n",
       "      <td>c Pringle b Klaassen</td>\n",
       "      <td>41</td>\n",
       "      <td>47</td>\n",
       "      <td>1</td>\n",
       "      <td>2</td>\n",
       "      <td>87.23</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>U.A.E.</td>\n",
       "      <td>3</td>\n",
       "      <td>Kashif Daud</td>\n",
       "      <td>b Pringle</td>\n",
       "      <td>15</td>\n",
       "      <td>14</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>107.14</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>U.A.E.</td>\n",
       "      <td>4</td>\n",
       "      <td>Vriitya Aravindâ€</td>\n",
       "      <td>c Klaassen b de Leede</td>\n",
       "      <td>18</td>\n",
       "      <td>21</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>85.71</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>U.A.E.</td>\n",
       "      <td>5</td>\n",
       "      <td>Zawar Farid</td>\n",
       "      <td>run out (Ackermann/â€ Edwards)</td>\n",
       "      <td>2</td>\n",
       "      <td>4</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>50.00</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                   match teamInnings  battingPos         batsmanName  \\\n",
       "0  U.A.E. Vs Netherlands      U.A.E.           1         Chirag Suri   \n",
       "1  U.A.E. Vs Netherlands      U.A.E.           2     Muhammad Waseem   \n",
       "2  U.A.E. Vs Netherlands      U.A.E.           3         Kashif Daud   \n",
       "3  U.A.E. Vs Netherlands      U.A.E.           4  Vriitya Aravindâ€    \n",
       "4  U.A.E. Vs Netherlands      U.A.E.           5         Zawar Farid   \n",
       "\n",
       "                        dismissal runs balls 4s 6s      SR  \n",
       "0    c â€ Edwards b van der Merwe   12    20  1  0   60.00  \n",
       "1            c Pringle b Klaassen   41    47  1  2   87.23  \n",
       "2                       b Pringle   15    14  0  1  107.14  \n",
       "3           c Klaassen b de Leede   18    21  0  0   85.71  \n",
       "4  run out (Ackermann/â€ Edwards)    2     4  0  0   50.00  "
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "with open('C:/Users/Dell/Desktop/python study material/t20_wc_batting_summary.json') as wc:\n",
    " data = json.load(wc)\n",
    "df_batting=pd.DataFrame(data[1]['battingSummary'])\n",
    "df_batting.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "44b825d5",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>match</th>\n",
       "      <th>bowlingTeam</th>\n",
       "      <th>bowlerName</th>\n",
       "      <th>overs</th>\n",
       "      <th>maiden</th>\n",
       "      <th>runs</th>\n",
       "      <th>wickets</th>\n",
       "      <th>economy</th>\n",
       "      <th>0s</th>\n",
       "      <th>4s</th>\n",
       "      <th>6s</th>\n",
       "      <th>wides</th>\n",
       "      <th>noBalls</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>Netherlands</td>\n",
       "      <td>Fred Klaassen</td>\n",
       "      <td>4</td>\n",
       "      <td>0</td>\n",
       "      <td>13</td>\n",
       "      <td>2</td>\n",
       "      <td>3.25</td>\n",
       "      <td>18</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>Netherlands</td>\n",
       "      <td>Tim Pringle</td>\n",
       "      <td>4</td>\n",
       "      <td>0</td>\n",
       "      <td>13</td>\n",
       "      <td>1</td>\n",
       "      <td>3.25</td>\n",
       "      <td>11</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>Netherlands</td>\n",
       "      <td>Logan van Beek</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "      <td>19</td>\n",
       "      <td>0</td>\n",
       "      <td>9.50</td>\n",
       "      <td>5</td>\n",
       "      <td>0</td>\n",
       "      <td>2</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>Netherlands</td>\n",
       "      <td>Bas de Leede</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>19</td>\n",
       "      <td>3</td>\n",
       "      <td>6.33</td>\n",
       "      <td>9</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>Netherlands</td>\n",
       "      <td>Paul van Meekeren</td>\n",
       "      <td>4</td>\n",
       "      <td>0</td>\n",
       "      <td>21</td>\n",
       "      <td>0</td>\n",
       "      <td>5.25</td>\n",
       "      <td>11</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                   match  bowlingTeam         bowlerName overs maiden runs  \\\n",
       "0  U.A.E. Vs Netherlands  Netherlands      Fred Klaassen     4      0   13   \n",
       "1  U.A.E. Vs Netherlands  Netherlands        Tim Pringle     4      0   13   \n",
       "2  U.A.E. Vs Netherlands  Netherlands     Logan van Beek     2      0   19   \n",
       "3  U.A.E. Vs Netherlands  Netherlands       Bas de Leede     3      0   19   \n",
       "4  U.A.E. Vs Netherlands  Netherlands  Paul van Meekeren     4      0   21   \n",
       "\n",
       "  wickets economy  0s 4s 6s wides noBalls  \n",
       "0       2    3.25  18  0  0     3       0  \n",
       "1       1    3.25  11  0  0     0       0  \n",
       "2       0    9.50   5  0  2     1       0  \n",
       "3       3    6.33   9  2  0     2       0  \n",
       "4       0    5.25  11  1  0     0       0  "
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "with open('C:/Users/Dell/Desktop/python study material/t20_wc_bowling_summary.json') as bs:\n",
    " data = json.load(bs)\n",
    "\n",
    "df_bowling=pd.DataFrame((data[1]['bowlingSummary']))\n",
    "df_bowling.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "a1dac734",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>name</th>\n",
       "      <th>team</th>\n",
       "      <th>battingStyle</th>\n",
       "      <th>bowlingStyle</th>\n",
       "      <th>playingRole</th>\n",
       "      <th>description</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Michael van Lingen</td>\n",
       "      <td>Namibia</td>\n",
       "      <td>Left hand Bat</td>\n",
       "      <td>Left arm Medium</td>\n",
       "      <td>Bowling Allrounder</td>\n",
       "      <td></td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Divan la Cock</td>\n",
       "      <td>Namibia</td>\n",
       "      <td>Right hand Bat</td>\n",
       "      <td>Legbreak</td>\n",
       "      <td>Opening Batter</td>\n",
       "      <td></td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Jan Nicol Loftie-Eaton</td>\n",
       "      <td>Namibia</td>\n",
       "      <td>Left hand Bat</td>\n",
       "      <td>Right arm Medium, Legbreak</td>\n",
       "      <td>Batter</td>\n",
       "      <td></td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Stephan Baard</td>\n",
       "      <td>Namibia</td>\n",
       "      <td>Right hand Bat</td>\n",
       "      <td>Right arm Medium fast</td>\n",
       "      <td>Batter</td>\n",
       "      <td></td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Gerhard Erasmus(c)</td>\n",
       "      <td>Namibia</td>\n",
       "      <td>Right hand Bat</td>\n",
       "      <td>Right arm Offbreak</td>\n",
       "      <td>Allrounder</td>\n",
       "      <td></td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                     name     team    battingStyle  \\\n",
       "0      Michael van Lingen  Namibia   Left hand Bat   \n",
       "1           Divan la Cock  Namibia  Right hand Bat   \n",
       "2  Jan Nicol Loftie-Eaton  Namibia   Left hand Bat   \n",
       "3           Stephan Baard  Namibia  Right hand Bat   \n",
       "4      Gerhard Erasmus(c)  Namibia  Right hand Bat   \n",
       "\n",
       "                 bowlingStyle         playingRole description  \n",
       "0             Left arm Medium  Bowling Allrounder              \n",
       "1                    Legbreak      Opening Batter              \n",
       "2  Right arm Medium, Legbreak              Batter              \n",
       "3       Right arm Medium fast              Batter              \n",
       "4          Right arm Offbreak          Allrounder              "
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "with open('C:/Users/Dell/Desktop/python study material/t20_wc_player_info.json') as pl:\n",
    " data = json.load(pl)\n",
    "df_player=pd.DataFrame(data)\n",
    "df_player.head() "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "cc6754f2",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>team1</th>\n",
       "      <th>team2</th>\n",
       "      <th>winner</th>\n",
       "      <th>margin</th>\n",
       "      <th>ground</th>\n",
       "      <th>matchDate</th>\n",
       "      <th>match_id</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Namibia</td>\n",
       "      <td>Sri Lanka</td>\n",
       "      <td>Namibia</td>\n",
       "      <td>55 runs</td>\n",
       "      <td>Geelong</td>\n",
       "      <td>Oct 16, 2022</td>\n",
       "      <td>T20I # 1823</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Netherlands</td>\n",
       "      <td>U.A.E.</td>\n",
       "      <td>Netherlands</td>\n",
       "      <td>3 wickets</td>\n",
       "      <td>Geelong</td>\n",
       "      <td>Oct 16, 2022</td>\n",
       "      <td>T20I # 1825</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Scotland</td>\n",
       "      <td>West Indies</td>\n",
       "      <td>Scotland</td>\n",
       "      <td>42 runs</td>\n",
       "      <td>Hobart</td>\n",
       "      <td>Oct 17, 2022</td>\n",
       "      <td>T20I # 1826</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Ireland</td>\n",
       "      <td>Zimbabwe</td>\n",
       "      <td>Zimbabwe</td>\n",
       "      <td>31 runs</td>\n",
       "      <td>Hobart</td>\n",
       "      <td>Oct 17, 2022</td>\n",
       "      <td>T20I # 1828</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Namibia</td>\n",
       "      <td>Netherlands</td>\n",
       "      <td>Netherlands</td>\n",
       "      <td>5 wickets</td>\n",
       "      <td>Geelong</td>\n",
       "      <td>Oct 18, 2022</td>\n",
       "      <td>T20I # 1830</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "         team1        team2       winner     margin   ground     matchDate  \\\n",
       "0      Namibia    Sri Lanka      Namibia    55 runs  Geelong  Oct 16, 2022   \n",
       "1  Netherlands       U.A.E.  Netherlands  3 wickets  Geelong  Oct 16, 2022   \n",
       "2     Scotland  West Indies     Scotland    42 runs   Hobart  Oct 17, 2022   \n",
       "3      Ireland     Zimbabwe     Zimbabwe    31 runs   Hobart  Oct 17, 2022   \n",
       "4      Namibia  Netherlands  Netherlands  5 wickets  Geelong  Oct 18, 2022   \n",
       "\n",
       "      match_id  \n",
       "0  T20I # 1823  \n",
       "1  T20I # 1825  \n",
       "2  T20I # 1826  \n",
       "3  T20I # 1828  \n",
       "4  T20I # 1830  "
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_match.rename({'scorecard':'match_id'}, axis = 1, inplace = True)\n",
    "df_match.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "3b88a2b4",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>match</th>\n",
       "      <th>teamInnings</th>\n",
       "      <th>battingPos</th>\n",
       "      <th>batsmanName</th>\n",
       "      <th>dismissal</th>\n",
       "      <th>runs</th>\n",
       "      <th>balls</th>\n",
       "      <th>4s</th>\n",
       "      <th>6s</th>\n",
       "      <th>SR</th>\n",
       "      <th>out/not_out</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>U.A.E.</td>\n",
       "      <td>1</td>\n",
       "      <td>Chirag Suri</td>\n",
       "      <td>c â€ Edwards b van der Merwe</td>\n",
       "      <td>12</td>\n",
       "      <td>20</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>60.00</td>\n",
       "      <td>out</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>U.A.E.</td>\n",
       "      <td>2</td>\n",
       "      <td>Muhammad Waseem</td>\n",
       "      <td>c Pringle b Klaassen</td>\n",
       "      <td>41</td>\n",
       "      <td>47</td>\n",
       "      <td>1</td>\n",
       "      <td>2</td>\n",
       "      <td>87.23</td>\n",
       "      <td>out</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>U.A.E.</td>\n",
       "      <td>3</td>\n",
       "      <td>Kashif Daud</td>\n",
       "      <td>b Pringle</td>\n",
       "      <td>15</td>\n",
       "      <td>14</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>107.14</td>\n",
       "      <td>out</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>U.A.E.</td>\n",
       "      <td>4</td>\n",
       "      <td>Vriitya Aravindâ€</td>\n",
       "      <td>c Klaassen b de Leede</td>\n",
       "      <td>18</td>\n",
       "      <td>21</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>85.71</td>\n",
       "      <td>out</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>U.A.E.</td>\n",
       "      <td>5</td>\n",
       "      <td>Zawar Farid</td>\n",
       "      <td>run out (Ackermann/â€ Edwards)</td>\n",
       "      <td>2</td>\n",
       "      <td>4</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>50.00</td>\n",
       "      <td>out</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>U.A.E.</td>\n",
       "      <td>6</td>\n",
       "      <td>Basil Hameed</td>\n",
       "      <td>c van der Merwe b de Leede</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>100.00</td>\n",
       "      <td>out</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>U.A.E.</td>\n",
       "      <td>7</td>\n",
       "      <td>Chundangapoyil Rizwan(c)</td>\n",
       "      <td>b de Leede</td>\n",
       "      <td>1</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>50.00</td>\n",
       "      <td>out</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>U.A.E.</td>\n",
       "      <td>8</td>\n",
       "      <td>Aayan Afzal Khan</td>\n",
       "      <td>c Cooper b Klaassen</td>\n",
       "      <td>5</td>\n",
       "      <td>7</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>71.42</td>\n",
       "      <td>out</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>U.A.E.</td>\n",
       "      <td>9</td>\n",
       "      <td>Karthik Meiyappan</td>\n",
       "      <td></td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>-</td>\n",
       "      <td>not_out</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>U.A.E.</td>\n",
       "      <td>10</td>\n",
       "      <td>Junaid Siddique</td>\n",
       "      <td></td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>not_out</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>Netherlands</td>\n",
       "      <td>1</td>\n",
       "      <td>Vikramjit Singh</td>\n",
       "      <td>b Basil Hameed</td>\n",
       "      <td>10</td>\n",
       "      <td>7</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "      <td>142.85</td>\n",
       "      <td>out</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                    match  teamInnings  battingPos               batsmanName  \\\n",
       "0   U.A.E. Vs Netherlands       U.A.E.           1               Chirag Suri   \n",
       "1   U.A.E. Vs Netherlands       U.A.E.           2           Muhammad Waseem   \n",
       "2   U.A.E. Vs Netherlands       U.A.E.           3               Kashif Daud   \n",
       "3   U.A.E. Vs Netherlands       U.A.E.           4        Vriitya Aravindâ€    \n",
       "4   U.A.E. Vs Netherlands       U.A.E.           5               Zawar Farid   \n",
       "5   U.A.E. Vs Netherlands       U.A.E.           6              Basil Hameed   \n",
       "6   U.A.E. Vs Netherlands       U.A.E.           7  Chundangapoyil Rizwan(c)   \n",
       "7   U.A.E. Vs Netherlands       U.A.E.           8          Aayan Afzal Khan   \n",
       "8   U.A.E. Vs Netherlands       U.A.E.           9         Karthik Meiyappan   \n",
       "9   U.A.E. Vs Netherlands       U.A.E.          10           Junaid Siddique   \n",
       "10  U.A.E. Vs Netherlands  Netherlands           1           Vikramjit Singh   \n",
       "\n",
       "                         dismissal runs balls 4s 6s      SR out/not_out  \n",
       "0     c â€ Edwards b van der Merwe   12    20  1  0   60.00         out  \n",
       "1             c Pringle b Klaassen   41    47  1  2   87.23         out  \n",
       "2                        b Pringle   15    14  0  1  107.14         out  \n",
       "3            c Klaassen b de Leede   18    21  0  0   85.71         out  \n",
       "4   run out (Ackermann/â€ Edwards)    2     4  0  0   50.00         out  \n",
       "5       c van der Merwe b de Leede    4     4  1  0  100.00         out  \n",
       "6                       b de Leede    1     2  0  0   50.00         out  \n",
       "7              c Cooper b Klaassen    5     7  0  0   71.42         out  \n",
       "8                                     0     0  0  0       -     not_out  \n",
       "9                                     0     1  0  0    0.00     not_out  \n",
       "10                  b Basil Hameed   10     7  2  0  142.85         out  "
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_batting['out/not_out'] = df_batting.dismissal.apply(lambda x:\"out\" if len (x) >0 else \"not_out\")\n",
    "df_batting.head(11)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "8e89604c",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>match</th>\n",
       "      <th>teamInnings</th>\n",
       "      <th>battingPos</th>\n",
       "      <th>batsmanName</th>\n",
       "      <th>dismissal</th>\n",
       "      <th>runs</th>\n",
       "      <th>balls</th>\n",
       "      <th>4s</th>\n",
       "      <th>6s</th>\n",
       "      <th>SR</th>\n",
       "      <th>out/not_out</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>U.A.E.</td>\n",
       "      <td>1</td>\n",
       "      <td>Chirag Suri</td>\n",
       "      <td>c  Edwards b van der Merwe</td>\n",
       "      <td>12</td>\n",
       "      <td>20</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>60.00</td>\n",
       "      <td>out</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>U.A.E.</td>\n",
       "      <td>2</td>\n",
       "      <td>Muhammad Waseem</td>\n",
       "      <td>c Pringle b Klaassen</td>\n",
       "      <td>41</td>\n",
       "      <td>47</td>\n",
       "      <td>1</td>\n",
       "      <td>2</td>\n",
       "      <td>87.23</td>\n",
       "      <td>out</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>U.A.E.</td>\n",
       "      <td>3</td>\n",
       "      <td>Kashif Daud</td>\n",
       "      <td>b Pringle</td>\n",
       "      <td>15</td>\n",
       "      <td>14</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>107.14</td>\n",
       "      <td>out</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>U.A.E.</td>\n",
       "      <td>4</td>\n",
       "      <td>Vriitya Aravind</td>\n",
       "      <td>c Klaassen b de Leede</td>\n",
       "      <td>18</td>\n",
       "      <td>21</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>85.71</td>\n",
       "      <td>out</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>U.A.E.</td>\n",
       "      <td>5</td>\n",
       "      <td>Zawar Farid</td>\n",
       "      <td>run out (Ackermann/ Edwards)</td>\n",
       "      <td>2</td>\n",
       "      <td>4</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>50.00</td>\n",
       "      <td>out</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>U.A.E.</td>\n",
       "      <td>6</td>\n",
       "      <td>Basil Hameed</td>\n",
       "      <td>c van der Merwe b de Leede</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>100.00</td>\n",
       "      <td>out</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>U.A.E.</td>\n",
       "      <td>7</td>\n",
       "      <td>Chundangapoyil Rizwan(c)</td>\n",
       "      <td>b de Leede</td>\n",
       "      <td>1</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>50.00</td>\n",
       "      <td>out</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>U.A.E.</td>\n",
       "      <td>8</td>\n",
       "      <td>Aayan Afzal Khan</td>\n",
       "      <td>c Cooper b Klaassen</td>\n",
       "      <td>5</td>\n",
       "      <td>7</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>71.42</td>\n",
       "      <td>out</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>U.A.E.</td>\n",
       "      <td>9</td>\n",
       "      <td>Karthik Meiyappan</td>\n",
       "      <td></td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>-</td>\n",
       "      <td>not_out</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>U.A.E.</td>\n",
       "      <td>10</td>\n",
       "      <td>Junaid Siddique</td>\n",
       "      <td></td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>not_out</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>Netherlands</td>\n",
       "      <td>1</td>\n",
       "      <td>Vikramjit Singh</td>\n",
       "      <td>b Basil Hameed</td>\n",
       "      <td>10</td>\n",
       "      <td>7</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "      <td>142.85</td>\n",
       "      <td>out</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>Netherlands</td>\n",
       "      <td>2</td>\n",
       "      <td>Max O'Dowd</td>\n",
       "      <td>b Junaid Siddique</td>\n",
       "      <td>23</td>\n",
       "      <td>18</td>\n",
       "      <td>3</td>\n",
       "      <td>1</td>\n",
       "      <td>127.77</td>\n",
       "      <td>out</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>Netherlands</td>\n",
       "      <td>3</td>\n",
       "      <td>Bas de Leede</td>\n",
       "      <td>c Rizwan b Meiyappan</td>\n",
       "      <td>14</td>\n",
       "      <td>18</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>77.77</td>\n",
       "      <td>out</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>Netherlands</td>\n",
       "      <td>4</td>\n",
       "      <td>Colin Ackermann</td>\n",
       "      <td>c Junaid Siddique b Aayan Afzal Khan</td>\n",
       "      <td>17</td>\n",
       "      <td>19</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>89.47</td>\n",
       "      <td>out</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>Netherlands</td>\n",
       "      <td>5</td>\n",
       "      <td>Tom Cooper</td>\n",
       "      <td>lbw b Junaid Siddique</td>\n",
       "      <td>8</td>\n",
       "      <td>16</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>50.00</td>\n",
       "      <td>out</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>Netherlands</td>\n",
       "      <td>6</td>\n",
       "      <td>Scott Edwards(c)</td>\n",
       "      <td></td>\n",
       "      <td>16</td>\n",
       "      <td>19</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>84.21</td>\n",
       "      <td>not_out</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>Netherlands</td>\n",
       "      <td>7</td>\n",
       "      <td>Roelof van der Merwe</td>\n",
       "      <td>b Junaid Siddique</td>\n",
       "      <td>0</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>out</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>Netherlands</td>\n",
       "      <td>8</td>\n",
       "      <td>Tim Pringle</td>\n",
       "      <td>b Zahoor Khan</td>\n",
       "      <td>15</td>\n",
       "      <td>16</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>93.75</td>\n",
       "      <td>out</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>Netherlands</td>\n",
       "      <td>9</td>\n",
       "      <td>Logan van Beek</td>\n",
       "      <td></td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>100.00</td>\n",
       "      <td>not_out</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                    match  teamInnings  battingPos               batsmanName  \\\n",
       "0   U.A.E. Vs Netherlands       U.A.E.           1               Chirag Suri   \n",
       "1   U.A.E. Vs Netherlands       U.A.E.           2           Muhammad Waseem   \n",
       "2   U.A.E. Vs Netherlands       U.A.E.           3               Kashif Daud   \n",
       "3   U.A.E. Vs Netherlands       U.A.E.           4          Vriitya Aravind    \n",
       "4   U.A.E. Vs Netherlands       U.A.E.           5               Zawar Farid   \n",
       "5   U.A.E. Vs Netherlands       U.A.E.           6              Basil Hameed   \n",
       "6   U.A.E. Vs Netherlands       U.A.E.           7  Chundangapoyil Rizwan(c)   \n",
       "7   U.A.E. Vs Netherlands       U.A.E.           8          Aayan Afzal Khan   \n",
       "8   U.A.E. Vs Netherlands       U.A.E.           9         Karthik Meiyappan   \n",
       "9   U.A.E. Vs Netherlands       U.A.E.          10           Junaid Siddique   \n",
       "10  U.A.E. Vs Netherlands  Netherlands           1           Vikramjit Singh   \n",
       "11  U.A.E. Vs Netherlands  Netherlands           2                Max O'Dowd   \n",
       "12  U.A.E. Vs Netherlands  Netherlands           3              Bas de Leede   \n",
       "13  U.A.E. Vs Netherlands  Netherlands           4           Colin Ackermann   \n",
       "14  U.A.E. Vs Netherlands  Netherlands           5                Tom Cooper   \n",
       "15  U.A.E. Vs Netherlands  Netherlands           6         Scott Edwards(c)    \n",
       "16  U.A.E. Vs Netherlands  Netherlands           7      Roelof van der Merwe   \n",
       "17  U.A.E. Vs Netherlands  Netherlands           8               Tim Pringle   \n",
       "18  U.A.E. Vs Netherlands  Netherlands           9            Logan van Beek   \n",
       "\n",
       "                               dismissal runs balls 4s 6s      SR out/not_out  \n",
       "0             c  Edwards b van der Merwe   12    20  1  0   60.00         out  \n",
       "1                   c Pringle b Klaassen   41    47  1  2   87.23         out  \n",
       "2                              b Pringle   15    14  0  1  107.14         out  \n",
       "3                  c Klaassen b de Leede   18    21  0  0   85.71         out  \n",
       "4           run out (Ackermann/ Edwards)    2     4  0  0   50.00         out  \n",
       "5             c van der Merwe b de Leede    4     4  1  0  100.00         out  \n",
       "6                             b de Leede    1     2  0  0   50.00         out  \n",
       "7                    c Cooper b Klaassen    5     7  0  0   71.42         out  \n",
       "8                                           0     0  0  0       -     not_out  \n",
       "9                                           0     1  0  0    0.00     not_out  \n",
       "10                        b Basil Hameed   10     7  2  0  142.85         out  \n",
       "11                     b Junaid Siddique   23    18  3  1  127.77         out  \n",
       "12                  c Rizwan b Meiyappan   14    18  1  0   77.77         out  \n",
       "13  c Junaid Siddique b Aayan Afzal Khan   17    19  1  0   89.47         out  \n",
       "14                 lbw b Junaid Siddique    8    16  0  0   50.00         out  \n",
       "15                                         16    19  0  0   84.21     not_out  \n",
       "16                     b Junaid Siddique    0     2  0  0    0.00         out  \n",
       "17                         b Zahoor Khan   15    16  0  0   93.75         out  \n",
       "18                                          4     4  0  0  100.00     not_out  "
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_batting['batsmanName'] = df_batting['batsmanName'].apply(lambda x:x.replace('â€',''))\n",
    "df_batting['dismissal'] = df_batting['dismissal'].apply(lambda x:x.replace('â€',''))\n",
    "df_batting.head(20)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "e42b44cd",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'Namibia Vs Sri Lanka': 'T20I # 1823',\n",
       " 'Sri Lanka Vs Namibia': 'T20I # 1823',\n",
       " 'Netherlands Vs U.A.E.': 'T20I # 1825',\n",
       " 'U.A.E. Vs Netherlands': 'T20I # 1825',\n",
       " 'Scotland Vs West Indies': 'T20I # 1826',\n",
       " 'West Indies Vs Scotland': 'T20I # 1826',\n",
       " 'Ireland Vs Zimbabwe': 'T20I # 1828',\n",
       " 'Zimbabwe Vs Ireland': 'T20I # 1828',\n",
       " 'Namibia Vs Netherlands': 'T20I # 1830',\n",
       " 'Netherlands Vs Namibia': 'T20I # 1830',\n",
       " 'Sri Lanka Vs U.A.E.': 'T20I # 1832',\n",
       " 'U.A.E. Vs Sri Lanka': 'T20I # 1832',\n",
       " 'Ireland Vs Scotland': 'T20I # 1833',\n",
       " 'Scotland Vs Ireland': 'T20I # 1833',\n",
       " 'West Indies Vs Zimbabwe': 'T20I # 1834',\n",
       " 'Zimbabwe Vs West Indies': 'T20I # 1834',\n",
       " 'Netherlands Vs Sri Lanka': 'T20I # 1835',\n",
       " 'Sri Lanka Vs Netherlands': 'T20I # 1835',\n",
       " 'Namibia Vs U.A.E.': 'T20I # 1836',\n",
       " 'U.A.E. Vs Namibia': 'T20I # 1836',\n",
       " 'Ireland Vs West Indies': 'T20I # 1837',\n",
       " 'West Indies Vs Ireland': 'T20I # 1837',\n",
       " 'Scotland Vs Zimbabwe': 'T20I # 1838',\n",
       " 'Zimbabwe Vs Scotland': 'T20I # 1838',\n",
       " 'Australia Vs New Zealand': 'T20I # 1839',\n",
       " 'New Zealand Vs Australia': 'T20I # 1839',\n",
       " 'Afghanistan Vs England': 'T20I # 1840',\n",
       " 'England Vs Afghanistan': 'T20I # 1840',\n",
       " 'Ireland Vs Sri Lanka': 'T20I # 1841',\n",
       " 'Sri Lanka Vs Ireland': 'T20I # 1841',\n",
       " 'India Vs Pakistan': 'T20I # 1842',\n",
       " 'Pakistan Vs India': 'T20I # 1842',\n",
       " 'Bangladesh Vs Netherlands': 'T20I # 1843',\n",
       " 'Netherlands Vs Bangladesh': 'T20I # 1843',\n",
       " 'South Africa Vs Zimbabwe': 'T20I # 1844',\n",
       " 'Zimbabwe Vs South Africa': 'T20I # 1844',\n",
       " 'Australia Vs Sri Lanka': 'T20I # 1845',\n",
       " 'Sri Lanka Vs Australia': 'T20I # 1845',\n",
       " 'England Vs Ireland': 'T20I # 1846',\n",
       " 'Ireland Vs England': 'T20I # 1846',\n",
       " 'Afghanistan Vs New Zealand': 'T20I # 1846a',\n",
       " 'New Zealand Vs Afghanistan': 'T20I # 1846a',\n",
       " 'Bangladesh Vs South Africa': 'T20I # 1847',\n",
       " 'South Africa Vs Bangladesh': 'T20I # 1847',\n",
       " 'India Vs Netherlands': 'T20I # 1848',\n",
       " 'Netherlands Vs India': 'T20I # 1848',\n",
       " 'Pakistan Vs Zimbabwe': 'T20I # 1849',\n",
       " 'Zimbabwe Vs Pakistan': 'T20I # 1849',\n",
       " 'Afghanistan Vs Ireland': 'T20I # 1849a',\n",
       " 'Ireland Vs Afghanistan': 'T20I # 1849a',\n",
       " 'Australia Vs England': 'T20I # 1849b',\n",
       " 'England Vs Australia': 'T20I # 1849b',\n",
       " 'New Zealand Vs Sri Lanka': 'T20I # 1850',\n",
       " 'Sri Lanka Vs New Zealand': 'T20I # 1850',\n",
       " 'Bangladesh Vs Zimbabwe': 'T20I # 1851',\n",
       " 'Zimbabwe Vs Bangladesh': 'T20I # 1851',\n",
       " 'Netherlands Vs Pakistan': 'T20I # 1852',\n",
       " 'Pakistan Vs Netherlands': 'T20I # 1852',\n",
       " 'India Vs South Africa': 'T20I # 1853',\n",
       " 'South Africa Vs India': 'T20I # 1853',\n",
       " 'Australia Vs Ireland': 'T20I # 1855',\n",
       " 'Ireland Vs Australia': 'T20I # 1855',\n",
       " 'Afghanistan Vs Sri Lanka': 'T20I # 1856',\n",
       " 'Sri Lanka Vs Afghanistan': 'T20I # 1856',\n",
       " 'England Vs New Zealand': 'T20I # 1858',\n",
       " 'New Zealand Vs England': 'T20I # 1858',\n",
       " 'Netherlands Vs Zimbabwe': 'T20I # 1859',\n",
       " 'Zimbabwe Vs Netherlands': 'T20I # 1859',\n",
       " 'Bangladesh Vs India': 'T20I # 1860',\n",
       " 'India Vs Bangladesh': 'T20I # 1860',\n",
       " 'Pakistan Vs South Africa': 'T20I # 1861',\n",
       " 'South Africa Vs Pakistan': 'T20I # 1861',\n",
       " 'Ireland Vs New Zealand': 'T20I # 1862',\n",
       " 'New Zealand Vs Ireland': 'T20I # 1862',\n",
       " 'Australia Vs Afghanistan': 'T20I # 1864',\n",
       " 'Afghanistan Vs Australia': 'T20I # 1864',\n",
       " 'England Vs Sri Lanka': 'T20I # 1867',\n",
       " 'Sri Lanka Vs England': 'T20I # 1867',\n",
       " 'Netherlands Vs South Africa': 'T20I # 1871',\n",
       " 'South Africa Vs Netherlands': 'T20I # 1871',\n",
       " 'Bangladesh Vs Pakistan': 'T20I # 1872',\n",
       " 'Pakistan Vs Bangladesh': 'T20I # 1872',\n",
       " 'India Vs Zimbabwe': 'T20I # 1873',\n",
       " 'Zimbabwe Vs India': 'T20I # 1873',\n",
       " 'New Zealand Vs Pakistan': 'T20I # 1877',\n",
       " 'Pakistan Vs New Zealand': 'T20I # 1877',\n",
       " 'England Vs India': 'T20I # 1878',\n",
       " 'India Vs England': 'T20I # 1878',\n",
       " 'England Vs Pakistan': 'T20I # 1879',\n",
       " 'Pakistan Vs England': 'T20I # 1879'}"
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "##Making match names combined to match other match columns in rest 3 tables.\n",
    "##I will connect these 4 tables using this column as primarykey\n",
    "match_id_dict= {}\n",
    "for index, row in df_match.iterrows():\n",
    "    key1 = row['team1']+\" Vs \"+row['team2']\n",
    "    key2 = row['team2']+\" Vs \"+row['team1']\n",
    "    match_id_dict[key1] = row[\"match_id\"]\n",
    "    match_id_dict[key2] = row[\"match_id\"]\n",
    "match_id_dict"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "596b63be",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>match</th>\n",
       "      <th>teamInnings</th>\n",
       "      <th>battingPos</th>\n",
       "      <th>batsmanName</th>\n",
       "      <th>dismissal</th>\n",
       "      <th>runs</th>\n",
       "      <th>balls</th>\n",
       "      <th>4s</th>\n",
       "      <th>6s</th>\n",
       "      <th>SR</th>\n",
       "      <th>out/not_out</th>\n",
       "      <th>match_id</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>U.A.E.</td>\n",
       "      <td>1</td>\n",
       "      <td>Chirag Suri</td>\n",
       "      <td>c  Edwards b van der Merwe</td>\n",
       "      <td>12</td>\n",
       "      <td>20</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>60.00</td>\n",
       "      <td>out</td>\n",
       "      <td>T20I # 1825</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>U.A.E.</td>\n",
       "      <td>2</td>\n",
       "      <td>Muhammad Waseem</td>\n",
       "      <td>c Pringle b Klaassen</td>\n",
       "      <td>41</td>\n",
       "      <td>47</td>\n",
       "      <td>1</td>\n",
       "      <td>2</td>\n",
       "      <td>87.23</td>\n",
       "      <td>out</td>\n",
       "      <td>T20I # 1825</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>U.A.E.</td>\n",
       "      <td>3</td>\n",
       "      <td>Kashif Daud</td>\n",
       "      <td>b Pringle</td>\n",
       "      <td>15</td>\n",
       "      <td>14</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>107.14</td>\n",
       "      <td>out</td>\n",
       "      <td>T20I # 1825</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>U.A.E.</td>\n",
       "      <td>4</td>\n",
       "      <td>Vriitya Aravind</td>\n",
       "      <td>c Klaassen b de Leede</td>\n",
       "      <td>18</td>\n",
       "      <td>21</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>85.71</td>\n",
       "      <td>out</td>\n",
       "      <td>T20I # 1825</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>U.A.E.</td>\n",
       "      <td>5</td>\n",
       "      <td>Zawar Farid</td>\n",
       "      <td>run out (Ackermann/ Edwards)</td>\n",
       "      <td>2</td>\n",
       "      <td>4</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>50.00</td>\n",
       "      <td>out</td>\n",
       "      <td>T20I # 1825</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>U.A.E.</td>\n",
       "      <td>6</td>\n",
       "      <td>Basil Hameed</td>\n",
       "      <td>c van der Merwe b de Leede</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>100.00</td>\n",
       "      <td>out</td>\n",
       "      <td>T20I # 1825</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>U.A.E.</td>\n",
       "      <td>7</td>\n",
       "      <td>Chundangapoyil Rizwan(c)</td>\n",
       "      <td>b de Leede</td>\n",
       "      <td>1</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>50.00</td>\n",
       "      <td>out</td>\n",
       "      <td>T20I # 1825</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>U.A.E.</td>\n",
       "      <td>8</td>\n",
       "      <td>Aayan Afzal Khan</td>\n",
       "      <td>c Cooper b Klaassen</td>\n",
       "      <td>5</td>\n",
       "      <td>7</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>71.42</td>\n",
       "      <td>out</td>\n",
       "      <td>T20I # 1825</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>U.A.E.</td>\n",
       "      <td>9</td>\n",
       "      <td>Karthik Meiyappan</td>\n",
       "      <td></td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>-</td>\n",
       "      <td>not_out</td>\n",
       "      <td>T20I # 1825</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>U.A.E. Vs Netherlands</td>\n",
       "      <td>U.A.E.</td>\n",
       "      <td>10</td>\n",
       "      <td>Junaid Siddique</td>\n",
       "      <td></td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>not_out</td>\n",
       "      <td>T20I # 1825</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                   match teamInnings  battingPos               batsmanName  \\\n",
       "0  U.A.E. Vs Netherlands      U.A.E.           1               Chirag Suri   \n",
       "1  U.A.E. Vs Netherlands      U.A.E.           2           Muhammad Waseem   \n",
       "2  U.A.E. Vs Netherlands      U.A.E.           3               Kashif Daud   \n",
       "3  U.A.E. Vs Netherlands      U.A.E.           4          Vriitya Aravind    \n",
       "4  U.A.E. Vs Netherlands      U.A.E.           5               Zawar Farid   \n",
       "5  U.A.E. Vs Netherlands      U.A.E.           6              Basil Hameed   \n",
       "6  U.A.E. Vs Netherlands      U.A.E.           7  Chundangapoyil Rizwan(c)   \n",
       "7  U.A.E. Vs Netherlands      U.A.E.           8          Aayan Afzal Khan   \n",
       "8  U.A.E. Vs Netherlands      U.A.E.           9         Karthik Meiyappan   \n",
       "9  U.A.E. Vs Netherlands      U.A.E.          10           Junaid Siddique   \n",
       "\n",
       "                      dismissal runs balls 4s 6s      SR out/not_out  \\\n",
       "0    c  Edwards b van der Merwe   12    20  1  0   60.00         out   \n",
       "1          c Pringle b Klaassen   41    47  1  2   87.23         out   \n",
       "2                     b Pringle   15    14  0  1  107.14         out   \n",
       "3         c Klaassen b de Leede   18    21  0  0   85.71         out   \n",
       "4  run out (Ackermann/ Edwards)    2     4  0  0   50.00         out   \n",
       "5    c van der Merwe b de Leede    4     4  1  0  100.00         out   \n",
       "6                    b de Leede    1     2  0  0   50.00         out   \n",
       "7           c Cooper b Klaassen    5     7  0  0   71.42         out   \n",
       "8                                  0     0  0  0       -     not_out   \n",
       "9                                  0     1  0  0    0.00     not_out   \n",
       "\n",
       "      match_id  \n",
       "0  T20I # 1825  \n",
       "1  T20I # 1825  \n",
       "2  T20I # 1825  \n",
       "3  T20I # 1825  \n",
       "4  T20I # 1825  \n",
       "5  T20I # 1825  \n",
       "6  T20I # 1825  \n",
       "7  T20I # 1825  \n",
       "8  T20I # 1825  \n",
       "9  T20I # 1825  "
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_batting['match_id'] = df_batting['match'].map(match_id_dict)\n",
    "df_batting.head(10)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "cdb2c05b",
   "metadata": {},
   "outputs": [],
   "source": [
    "df_match.to_csv('C:/Users/Dell/Desktop/T20_Match.csv', index = False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "b1b5ea2b",
   "metadata": {},
   "outputs": [],
   "source": [
    "df_batting.to_csv('C:/Users/Dell/Desktop/T20_Batting.csv', index = False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "id": "8426f0f4",
   "metadata": {},
   "outputs": [],
   "source": [
    "df_player.to_csv('C:/Users/Dell/Desktop/T20_Players.csv', index = False)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "6beb18ba",
   "metadata": {},
   "outputs": [],
   "source": [
    "df_bowling.to_csv('C:/Users/Dell/Desktop/T20_Bowling.csv', index = False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "21217eaa",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
